-- CHEK Content Service tables (MVP: 有知 + 相辅)
-- Naming convention: chek_content_*

CREATE TABLE IF NOT EXISTS chek_content_tag (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS chek_content_wiki_entry (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  slug VARCHAR(160) NOT NULL,
  title VARCHAR(120) NOT NULL,
  summary VARCHAR(500),
  body_md TEXT,
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  is_indexable BOOLEAN NOT NULL DEFAULT TRUE,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (slug),
  UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS chek_content_wiki_entry_tag (
  entry_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (entry_id, tag_id)
);

CREATE TABLE IF NOT EXISTS chek_content_post (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(120),
  body_md TEXT NOT NULL,
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  is_indexable BOOLEAN NOT NULL DEFAULT TRUE,
  occurred_at TIMESTAMP NULL,
  location_name VARCHAR(120),
  lng DECIMAL(10, 6),
  lat DECIMAL(10, 6),
  author_user_one_id VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chek_content_post_tag (
  post_id BIGINT NOT NULL,
  tag_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id, tag_id)
);

CREATE TABLE IF NOT EXISTS chek_content_post_media (
  post_id BIGINT NOT NULL,
  media_object_id BIGINT NOT NULL,
  kind VARCHAR(16) NOT NULL DEFAULT 'IMAGE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (post_id, media_object_id)
);

CREATE TABLE IF NOT EXISTS chek_content_comment (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  post_id BIGINT NOT NULL,
  body TEXT NOT NULL,
  author_user_one_id VARCHAR(64) NOT NULL,
  parent_comment_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
